login:
    path: /login
    controller: App\Controller\PageController::mainPage
    methods: GET

index:
    path: /
    controller: App\Controller\PageController::mainPage
    methods: GET

catch_all:
    path: /{any}
    controller: App\Controller\PageController::mainPage
    methods: GET
    requirements:
        any: .*