# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Common\Event\EventPublisher:
        arguments:
            $eventDispatcher: '@event_dispatcher'
        public: true

    App\Subject\App\Service\Listener\GroupDeletedEventListener:
        tags:
            - { name: 'kernel.event_listener', event: App\User\Domain\Service\Event\GroupDeletedEvent, method: '__invoke' }

    App\Subject\App\Service\Listener\UserDeletedEventListener:
        tags:
            - { name: 'kernel.event_listener', event: App\User\Domain\Service\Event\UserDeletedEvent, method: '__invoke' }

    App\Lesson\App\Service\Listener\CourseDeletedEventListener:
        tags:
            - { name: 'kernel.event_listener', event: App\Subject\Domain\Service\Event\CourseDeletedEvent, method: '__invoke' }

    App\Controller\AuthorizationApiHandler:
        tags:
            - { name: "open_api_server.api", api: "authorization"}

    App\Controller\UserApiHandler:
        tags:
            - { name: "open_api_server.api", api: "user" }

    App\Controller\SubjectApiHandler:
        tags:
            - { name: "open_api_server.api", api: "subject" }

    App\Controller\LessonApiHandler:
        tags:
            - { name: "open_api_server.api", api: "lesson" }

    App\Lesson\App\Query\LessonQueryServiceInterface:
        class: App\Lesson\App\Query\AuthorizedLessonQueryService
        arguments:
            $lessonQueryService: '@App\Lesson\Infrastructure\Query\LessonQueryService'