version: '3.8'

services:
  db:
    container_name: student-portal-db
    image: mirror.gcr.io/mysql:8.0.24
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: student_portal
    restart: always
    volumes:
      - .docker/data/db:/var/lib/mysql

  backend:
    build:
      context: ./backend
      args:
        APP_ENV: prod
    container_name: student-portal-backend
    restart: always
    environment:
      MYSQL_HOST: student-portal-db
    volumes:
      - ./backend/docker/php/php.ini-production:/usr/local/etc/php/php.ini
      - ./backend:/app
    depends_on:
      - db

  nginx:
    build: ./backend/docker/nginx
    container_name: student-portal-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend:/app
      - ./backend/docker/nginx/conf/ssl/:/etc/nginx/conf.d/ssl/
    depends_on:
      - db
      - backend

  frontend:
    build: ./frontend
    container_name: student-portal-frontend
    volumes:
      - ./backend:/backend
      - ./frontend:/frontend

volumes:
  db-data: {}