version: '3.8'

services:
  db:
    container_name: student-portal-db
    image: mirror.gcr.io/mysql:8.0.24
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: student_portal
    restart: always
    volumes:
      - .docker/data/db:/var/lib/mysql

  backend-api-generator:
    image: mirror.gcr.io/openapitools/openapi-generator-cli:v7.9.0
    command: generate -i /backend/api/student-portal-api.yaml -g php-symfony --additional-properties composerPackageName=openapitools/student-portal -o /backend/open-api
    volumes:
      - ./backend:/backend
    restart: no

  frontend-api-generator:
    image: mirror.gcr.io/openapitools/openapi-generator-cli:v7.9.0
    command: generate -i /app/backend/api/student-portal-api.yaml -g typescript-axios -o /app/frontend/src/shared/api
    volumes:
      - .:/app
    restart: no

  backend:
    build:
      context: ./backend
      args:
        APP_ENV: prod
    container_name: student-portal-backend
    restart: always
    environment:
      MYSQL_HOST: student-portal-db
    volumes:
      - ./backend/docker/php/php.ini-production:/usr/local/etc/php/php.ini
      - ./backend:/app
    depends_on:
      - db
      - backend-api-generator

  nginx:
    build: ./backend/docker/nginx
    container_name: student-portal-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend:/app
      - ./backend/docker/nginx/conf/ssl/:/etc/nginx/conf.d/ssl/
    depends_on:
      - db
      - backend

  frontend:
    build: ./frontend
    container_name: student-portal-frontend
    volumes:
      - ./backend:/backend
      - ./frontend:/frontend
    depends_on:
      - frontend-api-generator

volumes:
  db-data: {}