services:
  db:
    container_name: fool-portal-db
    image: mirror.gcr.io/mysql:8.0.24
    ports:
      - "4306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: fool_portal
    restart: always
    volumes:
      - .docker/data/db:/var/lib/mysql

  backend:
    build: ./backend
    container_name: fool-portal-backend
    restart: always
    environment:
      MYSQL_HOST: fool-portal-db
    ports:
      - '9000:9000'
    volumes:
      - ./backend:/app
    depends_on:
      - db

  nginx:
    build: ./backend/docker/nginx
    container_name: fool-portal-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend:/app
      - ./backend/docker/nginx/conf/ssl/:/etc/nginx/conf.d/ssl/
    depends_on:
      - db
      - backend

  frontend:
    build: ./frontend
    container_name: fool-portal-frontend
    volumes:
      - ./backend:/backend
      - ./frontend:/frontend

volumes:
  db-data: {}